work_dir: ./work_dir/ntu120/xsub/ctrgcn_mkd_bone

# feeder
feeder: feeders.multimodal_feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True


test_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False


# model
model: model.ctrgcn.Model
multi_model: model.ctrgcn.MultiModalGcn
student_model: model.ctrgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 65
nesterov: True

teacher_model:
  joint_model_weights: 'path-to-joint-teacher'
  bone_model_weights: 'path-to-bone-teacher'
  multi_model_weights: 'path-to-multimodal-teacher-model'
  logit_label_dir: 'path-to-pre-extracted-soft-label'
  student: multimodal
